(package "doom-modeline" "0.1.0" "A minimal and modern mode-line")

(website-url "https://github.com/seagle0128/doom-modeline")
(keywords "faces" "mode-line")

(package-file "doom-modeline.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(files "*.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "25.1")
(depends-on "compat")
(depends-on "nerd-icons")
(depends-on "shrink-path")

(development
 (depends-on "project")
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
